concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    # 👇 Fails because:
    #     - Not setting a proper write NPM token: can't publish
    #     - Tries to publish because first commit (init)
    #    It may also fail because:
    #     - GitHub token doesn't allow to create the release commit
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@v0.2.2

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
